apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  selector:
    name: demo
  clusterIP: None
  ports:
  - name: demo
    port: 1234
    targetPort: 1234
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-1
  labels:
    name: demo
spec:
  hostname: demo-1
  subdomain: demo
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-2
  labels:
    name: demo
spec:
  hostname: demo-2
  subdomain: demo
  containers:
  - name: nginx
    image: nginx
